### ISSUE TITLE
assetindexer.DoirhHXLq0KN6bXRhcjPC4- FcRdw~3D -->àīmbot``TAG: 2.13.3

### ISSUE THREAD

**Issue by karanrockstar** [karanrockstar/Blackshadow#2]
> àīmbot``TAG: 2.13.3(23031969)
ROOT: false
ABI: arm64-v8a
MODEL: M2103K19PI
SDK: 31
RELEASE: 12
---StackTrace---
java.io.IOException: Archive is not a ZIP archive
	at l..<init>(15XK:398)
	at l..<init>(15XK:98)
	at l..<init>(15XK:82)
	at l.۠ۛۥ.ۘ(CAPU:133)
	at l.ۜۥۗۗ.ۨ(T4WO:77)
	at l.ۡۥۗۗ.run(4ATC:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
TAG: 2.13.3(23031969)
ROOT: false
ABI: arm64-v8a
MODEL: M2103K19PI
SDK: 31
RELEASE: 12
---StackTrace---
java.io.IOException: Archive is not a ZIP archive
	at l..<init>(15XK:398)
	at l..<init>(15XK:98)
	at l..<init>(15XK:82)
	at l.۠ۛۥ.ۘ(CAPU:133)
	at l.ۜۥۗۗ.ۨ(T4WO:77)
	at l.ۡۥۗۗ.run(4ATC:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by karanrockstar** [comment]
assetindexer.DoirhHXLq0KN6bXRhcjPC4- FcRdw~3D -->àīmbot``TAG: 2.13.3
